### ISSUE TITLE
docker start  bug

### ISSUE THREAD

**Issue by WorldInMine** [wiktorn/Overpass-API#10]
hello, 
version: latest
desc: when i use docker start the overpass server , tips :

Reading XML file .../app/bin/init_osm3s.sh: line 44:    10 Broken pipe             bunzip2 < $PLANET_FILE
        11 Killed                  | $EXEC_DIR/bin/update_database --db-dir=$DB_DIR/ $META $COMPRESSION
 how to fix it;
thanks!

**Comment by WorldInMine** [comment]
the comand line:

docker run -e OVERPASS_META=yes -e OVERPASS_MODE=init -e OVERPASS_PLANET_URL=http://100.100.100.200/china-latest.osm.bz2 -e OVERPASS_DIFF_URL=http://download.openstreetmap.fr/replication/asia/china/hubei/minute/ -e OVERPASS_PLANET_SEQUENCE_ID=3457849 -e OVERPASS_RULES_LOAD=10 -v /big/docker/overpass_db/:/db -p 12345:81  -i -t --name overpass_china wiktorn/overpass-api

**Comment by wiktorn** [comment]
It looks like you might have run out of memory. How much memory do you have available? Did you try any smaller extracts? Did they fail in the same way?

**Comment by wiktorn** [comment]
Probably it's the same case as in #8. This is fixed in 89ada3f. You need to set `OVERPASS_FLUSH_SIZE=1`. This helps in memory constrained environments.
