### ISSUE TITLE
Push new build?

### ISSUE THREAD

**Issue by galewis2** [wiktorn/Overpass-API#102]
Would it be possible to get a new build pushed to Docker Hub, in particular with https://github.com/wiktorn/Overpass-API/commit/26e5b3fe4e8994333b915daff794693fcb4d4546 ? That didn't seem to have made it into latest

**Comment by wiktorn** [comment]
Sure, done. Sorry for the delay

**Comment by galewis2** [comment]
No worries, at the end of my K8s experimentation expect a PR
