### ISSUE TITLE
Change default of OVERPASS_CLONE_SOURCE to https

### ISSUE THREAD

**Issue by fawick** [wiktorn/Overpass-API#103]
In https://github.com/wiktorn/Overpass-API/blob/26e5b3fe4e8994333b915daff794693fcb4d4546/docker-entrypoint.sh#L9 the default for `OVERPASS_CLONE_SOURCE` is set to an HTTP-URL which (if taken verbatim) will result in HTTP 403. 

Using the same URL with the `https://`-scheme, however, will result in a working clone.

The following line lists the non-working HTTP-URL, too (there may be more occurrences, but that's the only ones I found so far):
https://github.com/wiktorn/Overpass-API/blob/26e5b3fe4e8994333b915daff794693fcb4d4546/README.md?plain=1#L11

**Comment by mathsteck** [comment]
Also having the same issue

**Comment by mmd-osm** [comment]
Fixed in https://github.com/drolbr/Overpass-API/issues/687
