### ISSUE TITLE
Clone overpass docker container with data to another VM issue

### ISSUE THREAD

**Issue by koldova** [wiktorn/Overpass-API#105]
Hello. I need to have running instance of Overpass with asia continent. I get the bz2 file from https://download.geofabrik.de/asia-latest.osm.bz2 and run overpass-api docker with -v to this file. The instance begins to generate files unter /db folder and it takes more than 20 hours by aws to get the service up and running. Thats why if I want to have the instance updated without huge downtime I want to run the overpass-api docker container on another vm and then after all the generation stuff is ready I want just copy the /db folder into the prod VM (dropping the existing one) and restart the docker container on prod. But it is not possible to copy the sockets "osm3s_v0.7.58_areas" and "osm3s_v0.7.58_osm_base". Thats why if i run the overpass-api docker on the prod again it fails saying the socket files are not found. Is there any solution for this?

**Comment by wiktorn** [comment]
Hi,

Sockets are objects that are used by runtime so it is not necessary to copy them. What you can do:
* once the new instance finishes initialization, shut it down, and just use this folder by your current instance
* copy the files while instance is shutdown (sockets should not be there)
* ignore the error about sockets

The other thing here is, that this is very expensive way to handle updates. You can set up to download [Geofabrik daily updates](http://download.geofabrik.de/asia-updates/) and you can apply them without shutting down *prod* instance. 

If you need to control, when updated database is released, you can clone the files you have and update the files in separate process / container. As long as you don't have updates running, the database is only read, so no issues with inconsistency. Then once this dataset is ready, you can deploy that on prod as described above.

**Comment by koldova** [comment]
Thank you for the answer. Is there a way to contact you personally? I mean 20 min call, even paid.  Because I have several different questions regarding this docker and it is urgent for now. My email for public contacts is kawinni806[at]gmail.com
