### ISSUE TITLE
Failed to process planet file

### ISSUE THREAD

**Issue by geocoderEU** [wiktorn/Overpass-API#109]
Hello,

i've trying to get an overpass-api container running. It works well, the container loads down the planet-File, but then exits with the error "Failed to process planet file". 
Detail output: 
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
.....
 99  855M   99  849M    0     0  2712k      0  0:05:23  0:05:20  0:00:03 3561k
 99  855M   99  853M    0     0  2715k      0  0:05:22  0:05:21  0:00:01 3638k
100  855M  100  855M    0     0  2718k      0  0:05:22  0:05:22 --:--:-- 3710k

Reading XML file ... elapsed node 2069525864. Compute current .../app/bin/init_osm3s.sh: line 44:   209 Broken pipe             bunzip2 < $PLANET_FILE

       210 Killed                  | $EXEC_DIR/bin/update_database --db-dir=$DB_DIR/ $META $COMPRESSION

Failed to process planet file
```

My docker run-statement looks as follows:
```
docker run -m 4096M --memory-reservation 4096M\
	-e OVERPASS_META=yes \
    -e OVERPASS_MODE=init \
    -e OVERPASS_PLANET_URL=https://download.geofabrik.de/europe/germany/baden-wuerttemberg-latest.osm.bz2 \
	-e OVERPASS_DIFF_URL=https://planet.openstreetmap.org/replication/minute/ \
    -e OVERPASS_RULES_LOAD=10 \
    -v /big/docker/overpass_db/:/db \
    -p 12347:80 \
    -i -t -d \
    --name docker.overpass_api.service wiktorn/overpass-api:latest
```

I've already tried it with 8GB of memory and with other planet files, but it had no effect.

Anything i'm overseeing here?

**Comment by geocoderEU** [comment]
Any suggestions here?

**Comment by wiktorn** [comment]
Sorry, I thought that I answered that already. Have you tried with more memory or with smaller extract, like Monaco?

**Comment by geocoderEU** [comment]
Hey there, Yes - i've tried it with more Memory and a few smaller extracts like austria, vienna, etc but with no effect. The same error pops up. :(

**Comment by wiktorn** [comment]
I tried with the Monaco on a Docker on Linux:
```

docker run -m 4096M --memory-reservation 4096M\
	-e OVERPASS_META=yes \
    -e OVERPASS_MODE=init \
    -e OVERPASS_PLANET_URL=https://download.geofabrik.de/europe/monaco-latest.osm.bz2 \
	-e OVERPASS_DIFF_URL=https://planet.openstreetmap.org/replication/minute/ \
    -e OVERPASS_RULES_LOAD=10 \
    -v /big/docker/overpass_db/:/db \
    -p 12347:80 \
    -i -t -d \
    --name docker.overpass_api.service wiktorn/overpass-api:latest
```

And the extract loaded correctly without issues.

But I noticed that you use https://planet.openstreetmap.org/replication/minute/ as a DIFF source. As this are full planet diffs, you'll be loading changes for the whole planet and your instance size will grow quickly.

Sorry, can't reproduce your issue.

**Comment by geocoderEU** [comment]
Hello wiktorn,

thanks for your try and the info. I'll then try a smaller DIFF Source.
