### ISSUE TITLE
Error when running the same query twice

### ISSUE THREAD

**Issue by alvasilvao** [wiktorn/Overpass-API#110]
Hi,

First of all thanks for this tool!

After installing, I quickly realized that I was getting the following error when running the same query twice. Is there any way to avoid this? 

```
The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.

Error: runtime error: open64: 0 Success /osm3s_osm_base Dispatcher_Client::request_read_and_idx::duplicate_query
```

If it helps, I installed it with this lines:

>   docker run \
>   -e OVERPASS_META=yes \
>   -e OVERPASS_MODE=clone \
>   -e OVERPASS_DIFF_URL=https://planet.openstreetmap.org/replication/day/ \
>   -e OVERPASS_RATE_LIMIT=100 \
>   -v /home/climbs/Documents/overpassturbo/overpass_clone_db/:/db \
>   -p 12346:80 \
>   -i -t \
>   --name overpass_world \
>   wiktorn/overpass-api

Thanks!

**Comment by wiktorn** [comment]
This repository is providing only Dockerfile for Overpass, not the tool itself, which is available [here](https://github.com/drolbr/Overpass-API). 

As far as I have checked, there is no way to remove duplicate query detection other than modifying the source code yourself.

**Comment by MennoSaey** [comment]
@alvasilvao did you find a solution to this. i am currently running into the same issue.

**Comment by alvasilvao** [comment]
Hi, I havent found a solution. What I have considered is to catch the error and restart the docker.

**Comment by MennoSaey** [comment]
Thanks for the quick reply, without changing anything it is now not throwing the error anymore and running fine. i wish i knew why it was doing it but for now it seems random. maybe the container is lagging and getting the same request twice? 
i didnt even restart the container when i got the error, the same instance is still running yet now it is working fine.

**Comment by MennoSaey** [comment]
looks like it is an overpass issue, more info here: [How to allow duplicate queries on an overpass-api custom server](https://stackoverflow.com/questions/76836002/how-to-allow-duplicate-queries-on-an-overpass-api-custom-server)
