### ISSUE TITLE
Docker status showing "health: starting" continuously

### ISSUE THREAD

**Issue by akhendra** [wiktorn/Overpass-API#111]
Hello Team,

I have launched asia docker instance using below commanda then docker started successfully.
sudo docker run \
  -e OVERPASS_META=yes \
  -e OVERPASS_MODE=init \
  -e OVERPASS_PLANET_URL=file:///db/asia-latest.osm.bz2 \
  -e OVERPASS_RULES_LOAD=0 \
  -e OVERPASS_UPDATE_SLEEP=36000000 \
  -v /osm-services/asia/overpass_db/:/db \
  -p 10001:80 \
  -i -t -d \
  --name overpass_asia wiktorn/overpass-api

But when I issued a command  #cat db/nodes.bin in shell terminal to see the content of "nodes.bin" under db then the docker status showing the "health: starting" continuously.
Please let me know what went wrong? what cases "health: starting" will come? how to fix it?y

when I see the docker logs, it shows "No database directory. Initializing"

**Comment by wiktorn** [comment]
The message `No database directory. Initializing` indicates that the container just started initializing the database. For whole Asia contintent, it may take a few days, depending on the hardware you're using for this.
