### ISSUE TITLE
[Question] How to update env vars after the container is created?

### ISSUE THREAD

**Issue by tylercubell** [wiktorn/Overpass-API#118]
I'm using Docker Desktop with WSL2 as the backend. After creating the Overpass whole world clone instance, I realized the `OVERPASS_ALLOW_DUPLICATE_QUERIES` environment variable is set to `no` by default, causing some API requests to fail. How would I be able to change this environment variable without re-creating the container and re-downloading the ~76G `nodes.bin` file?

**Comment by wiktorn** [comment]
If you mounted separate volume for db, then you can stop and remove existing container, and create a new one, with the changed environment variable.

If you didn't create a separate volume, I recommend stopping the container, moving the data to separate volume, and then do as explained above.

Without that, if you want to update version of the Overpass, you need to download the files again.
