### ISSUE TITLE
Memory issues when initializing container

### ISSUE THREAD

**Issue by leonixyz** [wiktorn/Overpass-API#17]
Hi,

I tried to initialize a container using a tarball of whole Europe (~32GB) on my machine having 8GB of memory and an SSD disk.

I expexted it would take a while but not so much... it's running since yesterday. After downloading the snapshot, my linux box started swapping and all I see from the output of the container is a buch of lines like:

- `Reading XML file.... elapsed way 267461502. Flushing the database...... done.` with the integer increasing
- and `Reorganizing the database.... done`.

Do you recommend me killing the process and trying something else? Or should I wait? I'm currently on vacation so i dont have any problem letting the machine run for another day.

Is there a way to predict more or less how much time is going to require until the end?

Is there a way to tweak the init run to avoid running into swapping issues?

Any suggestion?

Thanks in advance

**Comment by wiktorn** [comment]
8GB RAM for whole Europe seems smallish. It was minimum, that I had to allocate for processing Poland extract (~1GB of extract). You may try to set `OVERPASS_FLUSH_SIZE=1` in environment, but I'm not sure, if it will be enough, to fit import in 8GB of RAM.

I recommend disabling swap in docker. [Here](https://docs.docker.com/config/containers/resource_constraints/) you can learn, how to limit swap for a container.

For reference, importing Poland takes around 1-2 hours when no swap is used.

**Comment by leonixyz** [comment]
@wiktorn thank i will give it a try. Anyway, this issue is related to the overpass api itself, not to your docker image, right?

**Comment by wiktorn** [comment]
Exactly. overpass api is quite resource hungry during import/load. You can also try to download clone, but then you need to reserve space for whole world.

**Comment by wiktorn** [comment]
I guess you've managed to solve this issue?
