### ISSUE TITLE
Allow resume of initalization mode

### ISSUE THREAD

**Issue by JamesChevalier** [wiktorn/Overpass-API#18]
[This line](https://github.com/wiktorn/Overpass-API/blob/master/docker-entrypoint.sh#L35) of the `docker-entrypoint.sh` file prohibits us from resuming an initial build that has failed/stopped, but the `wget` usage in `download_clone.sh` [allows restarting](https://github.com/drolbr/Overpass-API/blob/master/src/bin/download_clone.sh#L82).

Perhaps it's still safe if this line changes to:

```
if [[ ! -d /db/db/diffs ]] ; then
```

**Comment by wiktorn** [comment]
Thank you for your submissions. What I'm thinking for this particular case is to add some sentinel file after download of clone has finished and use it to test, whether to try to download clone or startup normally.

However right now I'm really short on time and will get back to it in September. Sorry for delay,

**Comment by wiktorn** [comment]
Fixed in cfcd78fb94d20a01704dd7a87349897c356eaa88
