### ISSUE TITLE
How to run on local osm file?

### ISSUE THREAD

**Issue by yzlnew** [wiktorn/Overpass-API#22]
How to avoid using `OVERPASS_PLANET_URL`? I have generated an osm bz2 file of a specific region.

**Comment by wiktorn** [comment]
You can use file:/// URL to use your local file, remember to map your file inside the container.

Hope that helps

**Comment by yzlnew** [comment]
`file:///` doesn't work. Uploading local file to web server to get it working like charm. 👍

**Comment by wiktorn** [comment]
Did you point your `file:///` URL to the path inside container, where did you mount your custom osm.bz2 file?

**Comment by yzlnew** [comment]
Ok, I see. I point it to the location outside the container which obviously doesn't work. I'll mount the file to the container to see if it works.
Still new to docker.
