### ISSUE TITLE
Failed to process planet file

### ISSUE THREAD

**Issue by mullenkamp** [wiktorn/Overpass-API#29]
Hi,

I'm running into a problem running the docker image on a windows machine. I'm trying to run it for New Zealand using the geofabric site:

`docker run \
  -e OVERPASS_META=yes \
  -e OVERPASS_MODE=init \
  -e OVERPASS_PLANET_URL=http://download.geofabrik.de/australia-oceania/new-zealand-latest.osm.bz2 \
  -e OVERPASS_DIFF_URL=http://download.geofabrik.de/australia-oceania/new-zealand-updates/ \
  -e OVERPASS_RULES_LOAD=10 \
  -e OVERPASS_UPDATE_SLEEP=3600 \
  -v E:\ecan\deployments\overpass\NZ\:/db \
  -p 12345:80 \
  -i -t \
  --name overpass_nz wiktorn/overpass-api`

Gives me the error after initially processing the planet file:

`No database directory. Initializing
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  373M  100  373M    0     0  7075k      0  0:00:54  0:00:54 --:--:-- 6675k
[======================================================================] 100%
Reading XML file ... elapsed node 2945583286. /app/bin/init_osm3s.sh: line 44:    16 Broken pipe
    bunzip2 < $PLANET_FILE
        17 Killed                  | $EXEC_DIR/bin/update_database --db-dir=$DB_DIR/ $META $COMPRESSION
Failed to process planet file`

My guess is because it's a windows mount where the database sits rather than Linux? The sh script doesn't account for this?

Thanks!

**Comment by mullenkamp** [comment]
I can confirm my suspicions about the windows mount. I just tried it on Ubuntu and it ran fine.
Would it be possible to modify the sh script to accept windows mounts?

**Comment by wiktorn** [comment]
I'm not sure if there is anything I can do in the scripts to accept windows mounts. They should look indistinguishable from unix mounts.

Can I ask you for two things:
- Can you check if your Windows mounts supports unix domain sockets. Try installing netcat and run ` nc -lU aSocket.sock`
- are you sure that your docker machine has memory

**Comment by mullenkamp** [comment]
You were totally right. I need to stop thinking I know what I'm doing ;)
I hadn't allocated enough memory for the windows docker. I didn't realise that the initial run would require so much memory. Thank you very much for your help!
