### ISSUE TITLE
Increasing the dispatcher rate limit

### ISSUE THREAD

**Issue by andrepcg** [wiktorn/Overpass-API#33]
The dispatcher server receives an argument called `--rate-limit`. How to set this up using this docker image?

**Comment by wiktorn** [comment]
This haven't been on my radar till now. It should be fairly easy to extend, you just need to add necessary code to read environment variable here: [bin/dispatcher_start.sh](https://github.com/wiktorn/Overpass-API/blob/master/bin/dispatcher_start.sh).

Would you be willing to create pull request for that?

**Comment by wiktorn** [comment]
Closed by 8596920 and 6cb5465.
