### ISSUE TITLE
No (or empty) response form server - Request returns Error Code 403

### ISSUE THREAD

**Issue by 2Max4** [wiktorn/Overpass-API#35]
Hey there, 

if been trying to set up the overpass API for Germany. Therefore I used the provided script and modified it:
`docker run \
  -e OVERPASS_META=yes \
  -e OVERPASS_MODE=init \
  -e OVERPASS_PLANET_URL=http://download.geofabrik.de/europe/germany-latest.osm.bz2 \
  -e OVERPASS_DIFF_URL=http://download.openstreetmap.fr/replication/europe/germany/minute/ \
  -e OVERPASS_RULES_LOAD=10 \
  -v /big/docker/overpass_db/:/db \
  -p 12345:80 \
  -i -t \
  --name overpass_germany wiktorn/overpass-api`

it took a while but now everything is set up. I did the "docker start overpass_germany" comand and it booted. When i am now querying the server with "http;//<server_ip>:12345/api/  I do get error code 404.

Any ideas how I can fix it?

**Comment by 2Max4** [comment]
I fixed it - added the "interpreter" to the url and now I do get an response.
Still it is not working properly since the response itself is empty

`{'version': 0.6, 'generator': 'Overpass API 0.7.55.7 8b86ff77', 'osm3s': {'timestamp_osm_base': '2020-02-25T13:44:59Z', 'copyright': 'The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.'}, 'elements': []}`

I am sending the following request:
` api.get('area[name="{}"]; way(area)[highway][name]; out'.format(str("Berlin")),responseformat="json")`

which should return all streets in Berlin. When I run the request against: https://overpass.kumi.systems/api/ everything works fine... But not on my own system

**Comment by wiktorn** [comment]
The startup script doesn't create areas, they are created in background once the instance is started. Due to the fact, that this is second issue in quite recent time regarding this, I'll add step to create areas upfront. This will increase time to run through init phase (it may be like 25-50% longer)
