### ISSUE TITLE
overpass.errors.ServerRuntimeError: runtime error: Query ran out of memory 

### ISSUE THREAD

**Issue by 2Max4** [wiktorn/Overpass-API#36]
Hey I am getting the following error when quering the overpass API:

`overpass.errors.ServerRuntimeError: runtime error: Query ran out of memory in "query" at line 1. It would need at least 517 MB of RAM to continue.`

Since the server has 16GB of Ram and only 20% is in use - is there any way to give Overpass more memory ressources?

Greetings

**Comment by wiktorn** [comment]
Have you set `[maxsize=?]`? Per [documentation](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Element_limit_.28maxsize:.29) default limit is 512MB and I guess that this is the limit you're facing.
