### ISSUE TITLE
Failed to process planet file

### ISSUE THREAD

**Issue by arne182** [wiktorn/Overpass-API#37]
[ ok ]
osm:~# service docker start
 * Starting docker ...
 [ ok ]
osm:~# docker run \
>     -e OVERPASS_META=yes \
>     -e OVERPASS_MODE=init \
>     -e OVERPASS_PLANET_URL=https://download.geofabrik.de/europe/germany/baden-
wuerttemberg-latest.osm.bz2 \
>     -e OVERPASS_DIFF_URL=http://download.geofabrik.de/europe/germany/baden-wue
rttemberh-updates/ \
>     -e OVERPASS_RULES_LOAD=10 \
>     -v /big/docker/overpass_db/:/db \
>     -i -t \
>     --name overpass_bw wiktorn/overpass-api
No database directory. Initializing
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  717M  100  717M    0     0  1708k      0  0:07:09  0:07:09 --:--:-- 1602k
[======================================================================] 100%
Reading XML file ...terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/app/bin/init_osm3s.sh: line 44:    15 Broken pipe             bunzip2 < $PLANET_FE
        16 Aborted                 | $EXEC_DIR/bin/update_database --db-dir=$DB_DIN
Failed to process planet file

**Comment by arne182** [comment]
Looks like 1GB of RAM is too little. Will try again with two

**Comment by arne182** [comment]
2GB of RAM also failed. Trying 4GB.

**Comment by arne182** [comment]
4GB just failed but 4GB and cgroup_enable=memory swapaccount=1 with an 8GB swap worked. For a smaller 100M file

**Comment by arne182** [comment]
Would it be possible to load two regions into the same DB file?

**Comment by wiktorn** [comment]
Yes, it's possible. You would need to to point Overpass to extract that contains all needed regions, and then use [osmium](https://docs.osmcode.org/osmium/v1.11.1/osmium-extract.html) with `-p` in `OVERPASS_PLANET_PREPROCESS` to do the job for you. But this will handle only initial load, not updates. There is a small refactor needed, to handle that in update process too.

You would need also to create definitions of regions you want to extract in a file and mount it within your container.
