### ISSUE TITLE
It does not look like the update is working

### ISSUE THREAD

**Issue by arne182** [wiktorn/Overpass-API#39]
</osm>
Update finished with status code: 3
INFO: Using replication server at http://download.geofabrik.de/europe/germany/baden-wuerttemberg/tue/
DEBUG: Using given sequence ID 2593
DEBUG: Starting download at ID 2594 (max 100 MB)
Empty version, skipping file
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="libosmium/2.15.4">
</osm>

**Comment by wiktorn** [comment]
Can you post a bit more of log?

As far as I’ve checked your update URL there is no state.txt there:
http://download.geofabrik.de/europe/germany/baden-wuerttemberg/tue/state.txt

Please check your URL.

**Comment by arne182** [comment]
The URL got clipped
http://download.geofabrik.de/europe/germany/baden-wuerttemberg/tuebingen-regbez-updates/state.txt
Is the output above normal?

**Comment by wiktorn** [comment]
It might be once all updates are applied, that’s why asked for earlier logs.

**Comment by arne182** [comment]
I have had it up now for the last few days and it does seem to download when a new update is available but then it says 0 of ... And I see from my requests that my changes are not in the database.

**Comment by arne182** [comment]
![image](https://user-images.githubusercontent.com/844102/80857385-02c6a080-8c52-11ea-9536-a59e7b8e60c9.png)

**Comment by arne182** [comment]
After 0h51m51s: in "recurse", part 0, on line 255. Stack: 0 of 0 20897 of 0 0 of 0
After 0h52m8s: in "make-area", part 0, on line 257. Stack: 0 of 0 20937 of 0
INFO: Using replication server at http://download.geofabrik.de/europe/germany/baden-wuerttemberg/tue/
DEBUG: Using given sequence ID 2593
DEBUG: Starting download at ID 2594 (max 100 MB)
After 0h52m23s: in "make-area", part 0, on line 257. Stack: 0 of 0 20963 of 0
Empty version, skipping file
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="libosmium/2.15.4">
</osm>
Update finished with status code: 3
After 0h52m38s: in "make-area", part 0, on line 257. Stack: 0 of 0 21007 of 0
After 0h52m53s: in "recurse", part 0, on line 255. Stack: 0 of 0 21176 of 0 0 of 0
After 0h53m8s: in "make-area", part 0, on line 257. Stack: 0 of 0 21403 of 0
After 0h53m23s: in "recurse", part 0, on line 255. Stack: 0 of 0 21603 of 0 0 of 0
After 0h53m38s: in "make-area", part 0, on line 257. Stack: 0 of 0 21820 of 0
INFO: Using replication server at http://download.geofabrik.de/europe/germany/baden-wuerttemberg/tue/
After 0h53m53s: in "recurse", part 0DEBUG: Using given sequence ID 2593
DEBUG: Starting download at ID 2594 (max 100 MB)
, on line 255. Stack: 0 of 0 21955 of 0 0 of 0
Empty version, skipping file
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="libosmium/2.15.4">
</osm>
Update finished with status code: 3
After 0h54m8s: in "make-area", part 0, on line 257. Stack: 0 of 0 22115 of 0
After 0h54m23s: in "make-area", part 0, on line 257. Stack: 0 of 0 22273 of 0
After 0h54m38s: in "recurse", part 0, on line 255. Stack: 0 of 0 22465 of 0 0 of 0
INFO: Using replication server at http://download.geofabrik.de/europe/germany/baden-wuerttemberg/tue/
DEBUG: Using given sequence ID 2593
DEBUG: Starting download at ID 2594 (max 100 MB)
Empty version, skipping file
<?xml version='1.0' encoding='UTF-8'?>                                                               <osm version="0.6" generator="libosmium/2.15.4">
</osm>
Update finished with status code: 3                                                                  After 0h55m33s: in "osm-script", part 0, on line 2. Stack: 0 of 0                                    
</osm>
It took 3336 to run the loop. Desired load is: 10%. Sleeping: 30024                                  192.168.188.20 - - [01/May/2020:04:27:42 +0000] "POST /api/interpreter HTTP/1.1" 200 2301 "http://ov"INFO: Using replication server at http://download.geofabrik.de/europe/germany/baden-wuerttemberg/tue/DEBUG: Using given sequence ID 2593                                                                  DEBUG: Starting download at ID 2594 (max 100 MB)                                                     Empty version, skipping file                                                                         <?xml version='1.0' encoding='UTF-8'?>                                                               <osm version="0.6" generator="libosmium/2.15.4">                                                     </osm>                                                                                               Update finished with status code: 3

**Comment by wiktorn** [comment]
Interestingly enough the state file as well as Today’s osc file are empty on Geofabrik server. If the changes you’re referring are from yesterday it might explain the difference

**Comment by arne182** [comment]
Changes were the day before yesterday. Maybe it takes some time to update?

**Comment by wiktorn** [comment]
Your logs suggest that you should have all the changes in your database up to:
timestamp=2020-04-30T20\:59\:02Z

**Comment by arne182** [comment]
I will see when the change comes in. The picture above was for a change I made 01 May 2020 12:44. So it might be there tomorrow. So the replication looks like daily?

**Comment by wiktorn** [comment]
Frequency of changes depends on your source. Geofabrik prepares daily extracts. Though if the problem with today’s extract will not be fixed, you may not see your changes until some other changes will be made to these objects

**Comment by arne182** [comment]
Is it possible to use an update from say the whole of germany being applied to a smaller part of Germany?
Today it looks like the 
http://download.geofabrik.de/europe/germany/baden-wuerttemberg/tuebingen-regbez-updates/state.txt
is updated but the files 594
http://download.geofabrik.de/europe/germany/baden-wuerttemberg/tuebingen-regbez-updates/000/002/
are missing

**Comment by arne182** [comment]
Now it looks like this
![image](https://user-images.githubusercontent.com/844102/80941877-cd51bc80-8de3-11ea-82d3-84dcf3c3aac6.png)
after an hour with this output
![image](https://user-images.githubusercontent.com/844102/80942049-291c4580-8de4-11ea-8e27-41a4e5fb2e03.png)
looks like it is getting stuck somewhere.

**Comment by arne182** [comment]
after deleting the changes.osm the newly downloaded file did apply properly, but still have this way in my database that should have been deleted
![image](https://user-images.githubusercontent.com/844102/81398441-82101480-9129-11ea-8719-a19f009ab085.png)

**Comment by wiktorn** [comment]
I'd recommend rewinding `/db/replicate_id` to 2592. The broken file was downloaded and failed to apply, you haven't replaced it with proper version, so update went further. There is no risk, in applying updates once again.

To answer your earlier question, no, it's not yet possible to use updates from e.g. Germany or even planet file, and apply only part of it. Though it shouldn't be that hard to set, as `osmium` is already installed within docker (see [docs](https://docs.osmcode.org/osmium/latest/osmium-extract.html)). Though scripts needs a bit of tweaking to allow for that. Though I'm not sure, if bbox extracting is enough, or based by shape.

Pull requests are most welcome.

**Comment by arne182** [comment]
I set the replicate_id to 2592 and then the updates ran through with only this one error
![image](https://user-images.githubusercontent.com/844102/81469908-0fb23980-91e8-11ea-8e26-3c50f49a39cd.png)
.
still with https://www.openstreetmap.org/way/783101000 included in the result

**Comment by arne182** [comment]
I see it in 2594

![image](https://user-images.githubusercontent.com/844102/81470124-49d00b00-91e9-11ea-9da1-88bc8999f1d2.png)

It just does not apply that. It does not bother me too much as long as everything else works. It is just interesting that this way is not being deleted

**Comment by wiktorn** [comment]
Can you paste full error after `/app/bin/update_database` ? It looks like the updated wasn't applied at all.

**Comment by arne182** [comment]
Changes I made two days ago are in the db. I would need to do it again.

**Comment by wiktorn** [comment]
Missing changes were fixed in e4881f5eca786267a077ed4661b9d6a90f1da011
