### ISSUE TITLE
Is it possible to clip diffs according to a polygon?

### ISSUE THREAD

**Issue by zdila** [wiktorn/Overpass-API#43]
Hello,

We are interested only for a small region of central europe. We can extract it from planet file and use it for `OVERPASS_PLANET_URL`. Is it possible to apply our clipping polygon from GeoJSON file to minutely diffs?

**Comment by wiktorn** [comment]
As mentioned in #37 (in this [comment](https://github.com/wiktorn/Overpass-API/issues/37#issuecomment-629595835)) this would need small refactor to preprocess both planet file on init and continue to do the same when applying diff. I hadn't had time to do it myself, but I will happily welcome any patches implementing that.
