### ISSUE TITLE
Option for (currently static) nginx timeouts?

### ISSUE THREAD

**Issue by ghost** [wiktorn/Overpass-API#46]
First of all @wiktorn , thank you for this Docker image! Even for someone who is just starting to learn Docker it was very easy to setup an overpass server with the help of this image.

While I was running some tests today querying my docker overpass instance through `wget`, I noticed that the connection to the server was reset roughly every 16 minutes. As my query needs to run longer (this is the main reason for my private overpass instance), `wget` then started a second query which resulted in the same two queries being executed on the server at the same time with an offset of 16 mins.

The culprit in this case is the `fastcgi_read_timeout  1000s;` directive in `nginx.conf`. 

So my question/feature request is to pass that value as an argument to `docker run` if possible. Alternatively one could think about a higher default value (like 24 hours or so).

Thanks and best regards!

[**Edit**] Changed `keepalive_timeout` to `fastcgi_read_timeout`.

**Comment by ghowen** [comment]
It looks like the culprit is rather the ` fastcgi_read_timeout 1000s;`. I'll keep experimenting.

**Comment by ghowen** [comment]
It is the `fastcgi_read_timeout`. Setting it to `14400` allowed me to finish my overpass query (found ~1M elements in 26 mins) and download the results (450M in 21 mins). So this needs to be either configurable or set to a higher value per default to allow longer queries (which is probably one of the main reasons to setup a private Overpass server).

**Comment by wiktorn** [comment]
Thank you for elaborate bug report and testing, what actually needs to be changed, that helped a lot. Bear in mind, that images needs some time to regenerate on Docker Hub (6h or more AFAIR).
