### ISSUE TITLE
Log Nginx Errors

### ISSUE THREAD

**Issue by boldtrn** [wiktorn/Overpass-API#52]
Sometimes I receive wird Nginx errors when accessing the Overpass instance. The error contains a hint to check the Nginx error log, but I don't think the container is writing logs? Maybe it would be possible to also write the Nginx logs to the disk?

**Comment by wiktorn** [comment]
nginx logs are written to `/var/log/nginx/error.log` which are symlinked to `stderr`. `docker logs` (or any other tool that you use to gather logs from docker) should contain nginx error log

**Comment by boldtrn** [comment]
Thanks a lot for the reply. IIRC, I checked `docker logs` and I could not see the nginx logs. It has been some time and luckily the errors I saw did not show up again.
