### ISSUE TITLE
No such file or directory /db/db//osm3s_v0.7.55_areas Unix_Socket::7

### ISSUE THREAD

**Issue by fabianofrancesconi** [wiktorn/Overpass-API#54]
Hello! First of all thank you for this work and for your support 👍 

I have this issue with the container and that prevents areas queries to work. I read here and there and you said multiple times that areas are calculated as part of the execution o the container. In the initialization phase, I have seen multiple times messages about different parts of the "pipeline" being processed but, once it stopped and I restarted it, I see all "good" messages on the stdout/stderr except one nasty line:

`runtime error: open64: 2 No such file or directory /db/db//osm3s_v0.7.55_areas Unix_Socket::7`

Of course such file does not exist. Is there a way to trigger a `make-area` stage? Is there a way to see whether there's one running? How can I best troubleshoot why this file is not there and why I get this error? Thanks!

I tried the following command:

```
curl -g 'http://localhost:12345/api/interpreter?data=[out:json];area[name="Berlin"];out;'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" lang="en"/>
  <title>OSM3S Response</title>
</head>
<body>

<p>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</p>
<p><strong style="color:#FF0000">Error</strong>: runtime error: open64: 2 No such file or directory /db/db//osm3s_v0.7.55_areas Unix_Socket::7 </p>

</body>
</html>
```

I have bootstrapped the container with only Germany and the `rules_loop.log` is filled with "updates started/finished" messages.

**Comment by fabianofrancesconi** [comment]
After restarting the container now I get a different error

`line 29: static error: Unknown attribute "return-area" in element "make-area".`

**Comment by wiktorn** [comment]
Hi,

Sorry for coming back so late. The first error:
> runtime error: open64: 2 No such file or directory /db/db//osm3s_v0.7.55_areas Unix_Socket::

Suggests, that areas dispatcher is not running. Lack of the specified file might be either to the problem in dispatcher startup or specific host configuration that prevents using of unix domain sockets.

Can you check if you have this process running:
`/app/bin/dispatcher --osm-base --db-dir=/db/db --meta`
?

Which version of Overpass are you running?

**Comment by fabianofrancesconi** [comment]
Actually I realized I was running an old version of this tool. We can close it here.
Thanks for the answer nonetheless!
