### ISSUE TITLE
File_Error Operation not permitted

### ISSUE THREAD

**Issue by brestmoor** [wiktorn/Overpass-API#71]
Hello,

I am deploying overpass-api on Azure Container Instances with command:

    docker 
      -e OVERPASS_META=yes  
      -e OVERPASS_MODE=init  
      -e OVERPASS_PLANET_URL=http://download.geofabrik.de/europe/monaco-latest.osm.bz2  
      -e OVERPASS_RULES_LOAD=10 
      -p 80:80 -v overpassmonaco/test-volume4:/db  
      --name overpass-monaco

After running the container for the first time everyting seems fine. I get the message:

    Overpass ready, you can start your container with docker start

However on the second run these are the logs I get:

    File_Error Operation not permitted 1 /db/db//osm3s_v0.7.55_areas Unix_Socket::4
    2021-05-23 10:07:35,142 INFO exited: dispatcher_areas (exit status 0; not expected)

The API isn't working and the only response for HTTP requests is:
runtime error: The dispatcher (i.e. the database management system) is turned off.

What is the reason for these errors and how could I fix them?

**Comment by wiktorn** [comment]
Are you sure that your system supports both Unix Domain sockets and Shared memory?

**Comment by brestmoor** [comment]
Honestly I don't know, but I guess that may be the issue, if this is the first thing that came to your mind. I can't really find any documentation for ACI regarding Unix Domain sockets or Shared memory support.

**Comment by scorsi** [comment]
Hello @wiktorn,
Is that issue related to Unix Domain Socket / Shared Memory ?
If so, do you know if it is specific to your docker image or directly to Overpass itself ? (to know if creating my own Docker image would do the trick or not)

**Comment by wiktorn** [comment]
This is related to Overpass itself, both are used by the Overpass.
