### ISSUE TITLE
Nothing happens after download is over

### ISSUE THREAD

**Issue by cbouyssi** [wiktorn/Overpass-API#73]
Hello,

We've been trying to run overpass on docker using the following command : 

`docker run   
-e OVERPASS_META=yes   
-e OVERPASS_MODE=init   
-e OVERPASS_PLANET_URL=https://download.geofabrik.de/europe/france-latest.osm.bz2 
-e OVERPASS_DIFF_URL=http://download.openstreetmap.fr/replication/europe/france/minute/   
-e OVERPASS_RULES_LOAD=10   
-v /osm/db/:/db   
-p 8081:80   
-i -t   
--name overpass_monaco wiktorn/overpass-api`

The download starts and finishes, we can see the file in the db/ from the container but then nothing happens. 
We tried stoping the container manually and restart it, but download starts again, the file get replaced and then nothing happens again.

Any idea of what we're doing wrong ?

Thanks for your help

**Comment by wiktorn** [comment]
Hi,

docker logs would help diagnose your situation - or output to the console if you run it in interactive mode. 

How much memory does your Docker container have at its disposal?

**Comment by cbouyssi** [comment]
Thanks for your response. We don't see any logs from docker after the DL of the openstreetmap data is over (we see the DL progress, then the files in db/ and then nothing happens).
We run docker on a debian VM with 15Gb of RAM (without restriction for the container use)

**Comment by wiktorn** [comment]
Looks like you should have enough memory for that. After one hour, I've got following output
```
Unable to find image 'wiktorn/overpass-api:latest' locally
latest: Pulling from wiktorn/overpass-api
ac2522cc7269: Already exists
d0371f2533b8: Already exists
7c732fa8fb45: Already exists
9758a18ccb2b: Already exists
fc5d72c8e20d: Already exists
295f5c8b7650: Pull complete
a05887e4cb79: Pull complete
4c2c06e1ab2f: Pull complete
54a63ef30ec4: Pull complete
a39cea320aaa: Pull complete
b98473d0b9c7: Pull complete
b2dde7e4674f: Pull complete
bfd5951b185d: Pull complete
e9796441ecc9: Pull complete
1a8e093c752c: Pull complete
1cbfe625a6b3: Pull complete
bc15852417c6: Pull complete
Digest: sha256:c4da71fd7b8d2a81d2f37d62cca885366d607c8c1e62e70b24e4090595b6661f
Status: Downloaded newer image for wiktorn/overpass-api:latest
No database directory. Initializing
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6023M  100 6023M    0     0  18.2M      0  0:05:30  0:05:30 --:--:-- 12.7M
Reading XML file ... elapsed node 514445197. Flushing to database ...... done.
Reading XML file ... elapsed node 720342114. Flushing to database ...... done.
Reading XML file ... elapsed node 805664302. Flushing to database ...... done.
Reading XML file ... elapsed node 864996214. Flushing to database ...... done.
Reading XML file ... elapsed node 938753230. Flushing to database ...... done.
Reading XML file ... elapsed node 1019646610. Flushing to database ...... done.
Reading XML file ... elapsed node 1167275336. Flushing to database ...... done.
Reading XML file ... elapsed node 1296686581. Flushing to database ...... done.
Reading XML file ... elapsed node 1398477285. Flushing to database ...... done.
Reading XML file ... elapsed node 1521145223. Flushing to database ...... done.
Reading XML file ... elapsed node 1645783787. Flushing to database ...... done.
Reading XML file ... elapsed node 1767441901. Flushing to database ...... done.
Reading XML file ... elapsed node 1918004409. Flushing to database ...... done.
Reading XML file ... elapsed node 2093394095. Flushing to database ...... done.
Reading XML file ... elapsed node 2317108577. Flushing to database ...... done.
Reading XML file ... elapsed node 2483766494. Flushing to database ...... done.
Reorganizing the database ...
```

Probably it will take another few (or a dozen of) hours to fully load this extract.

How long did you wait for the output?

**Comment by cbouyssi** [comment]
Thanks for your answer, the problem was simply that we weren't waiting enough. It took a couple of hours indeed !
