### ISSUE TITLE
Expected container size?

### ISSUE THREAD

**Issue by larsschwarz** [wiktorn/Overpass-API#77]
After the initial setup up I noticed that the container took all available diskspace even though I only used a country extract, not the whole planet file. The container size now is 131 GB. 

ways.bin has 31 GB
nodes.bin has 51 GB
nodes.map has 35 GB

Does this sound expected for using a country extract (Germany) only?

**Comment by wiktorn** [comment]
Did you enable compression? I have 11GB for Poland extract with compression enabled, but when it was ~40GB previously and I'm not sure, if the compression was enabled properly in previous versions. And Germany osm.pbf extract is more than twice as big as Poland's one, so these sizes are nothing unexpected.

**Comment by larsschwarz** [comment]
I just ran the default example commands, so yes (using gz). Closing this issue then. Thanks!
