### ISSUE TITLE
Docker container does not stop after initialization

### ISSUE THREAD

**Issue by samuelefiorini** [wiktorn/Overpass-API#80]
As reported [here](https://hub.docker.com/r/wiktorn/overpass-api):

> _After initialization is finished, the Docker container will stop_

but in my case this is not happening. The container keeps running and it is ready to accept requests.

This is the command I'm using:

```
docker run \
   -e OVERPASS_META=yes \
   -e OVERPASS_MODE=init \
   -e OVERPASS_PLANET_URL=http://download.geofabrik.de/europe/monaco-latest.osm.bz2 \
   -e OVERPASS_DIFF_URL=http://download.openstreetmap.fr/replication/europe/monaco/minute/ \
   -v /overpass_db:/db \
   -t \
   wiktorn/overpass-api
```

I need it to stop because after the initialization step I would upload `overpass_db` to S3.

What am I missing?

**Comment by wiktorn** [comment]
My bad, you miss nothing. This is effect of #75. I'll fix that keeping instance running after initialization will be optional.

Also, Docker hub docs needs update.
