### ISSUE TITLE
OVERPASS_STOP_AFTER_INIT has no effect in the clone mode

### ISSUE THREAD

**Issue by CezaryTarnowski-TomTom** [wiktorn/Overpass-API#89]
I can see that in the clone mode the config OVERPASS_STOP_AFTER_INIT is ignored and the container is restarting regardless of the value of the flag.

My question is are there any technical limitations or this is just a bug.

If that's just a bug I can propose a PR to fix that.

**Comment by wiktorn** [comment]
I'm pretty sure that this was overlooked and it's a bug. PR is most welcomed.
