### ISSUE TITLE
Problem after importing data

### ISSUE THREAD

**Issue by ubergesundheit** [wiktorn/Overpass-API#9]
I tried to create an overpass instance out of tags `wiktorn/overpass-api:latest` and `wiktorn/overpass-api:0.7.55` but after importing, the container seems to fail.

Here's what I did:

```
docker volume create overpass
docker run \
  -e OVERPASS_META=yes \
  -e OVERPASS_MODE=init \
  -e OVERPASS_PLANET_URL=http://download.geofabrik.de/europe/germany/nordrhein-westfalen/muenster-regbez-latest.osm.bz2 \
  -e OVERPASS_DIFF_URL=https://planet.openstreetmap.org/replication/minute/ \
  -v overpass:/db \
  -p 12345:80 \
  -i -t \
  --name overpass_muenster wiktorn/overpass-api

docker start overpass_muenster
```

The logs of the `overpass_muenster` container are:

```
Reading XML file ... finished reading nodes. Flushing to database ...... done.                                            
Reading XML file ... elapsed way 320277976. Flushing to database ...... done.
Reading XML file ... finished reading ways. Flushing to database ...... done.
Reorganizing the database ... done.
Reading XML file ... finished reading relations. compute_geometry: Way 6654659 used in relation 4531 not found.
compute_geometry: Way 6650667 used in relation 4531 not found.
compute_geometry: Way 6651330 used in relation 4531 not found.
compute_geometry: Way 6651327 used in relation 4531 not found.
compute_geometry: Way 112448606 used in relation 4531 not found.

... many more of these ...

compute_geometry: Way 32731138 used in relation 9332852 not found.
compute_geometry: Way 30016603 used in relation 9332852 not found.
compute_geometry: Way 528727430 used in relation 9332852 not found.
compute_geometry: Way 37560917 used in relation 9332852 not found.
compute_geometry: Way 329748412 used in relation 9332852 not found.
Flushing to database ....... done.
Update complete.
Overpass ready, you can start your container with docker start
2019-03-05 21:42:31,815 CRIT Supervisor running as root (no user in config file)
2019-03-05 21:42:31,820 INFO supervisord started with pid 1
2019-03-05 21:42:32,824 INFO spawned: 'overpass_dispatch' with pid 8
2019-03-05 21:42:32,828 INFO spawned: 'nginx' with pid 9
2019-03-05 21:42:32,835 INFO spawned: 'fcgiwrap' with pid 10
2019-03-05 21:42:32,837 INFO spawned: 'apply_diff' with pid 11
2019-03-05 21:42:32,839 INFO spawned: 'fetch_diff' with pid 12
2019-03-05 21:42:32,841 INFO spawned: 'dispatcher_areas' with pid 13
2019-03-05 21:42:32,847 INFO spawned: 'areas_rules' with pid 18
2019-03-05 21:42:32,872 INFO exited: fetch_diff (exit status 1; not expected)
2019-03-05 21:42:33,876 INFO success: overpass_dispatch entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-03-05 21:42:33,876 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-03-05 21:42:33,876 INFO success: fcgiwrap entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-03-05 21:42:33,876 INFO success: apply_diff entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-03-05 21:42:33,878 INFO spawned: 'fetch_diff' with pid 44
2019-03-05 21:42:33,878 INFO success: dispatcher_areas entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-03-05 21:42:33,878 INFO success: areas_rules entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-03-05 21:42:33,892 INFO exited: fetch_diff (exit status 1; not expected)
2019-03-05 21:42:35,896 INFO spawned: 'fetch_diff' with pid 53
2019-03-05 21:42:35,909 INFO exited: fetch_diff (exit status 1; not expected)
2019-03-05 21:42:38,914 INFO spawned: 'fetch_diff' with pid 67
2019-03-05 21:42:38,928 INFO exited: fetch_diff (exit status 1; not expected)
2019-03-05 21:42:38,928 INFO gave up: fetch_diff entered FATAL state, too many start retries too quickly
```

**Comment by wiktorn** [comment]
I guess that you're missing `OVERPASS_PLANET_SEQUENCE_ID` environment variable. You need this, to reflect, how the dump that you're loaded is positioned against minute diff repository. Each diff repository has its own sequence so you need to check the one that you choose for correct number.

Please bear in mind, that though you've loaded only one Land, your diffs will be updating your database with whole planet so you will have partial (but growing) data from other parts of the world.

**Comment by ubergesundheit** [comment]
Thanks for your answer, how to find the sequence id though?

As per your suggestion I switched to `http://download.openstreetmap.fr/replication/europe/germany/nordrhein_westfalen/munster/minute/` for the diff_url and `3397105` (which is the `sequenceNumber` from [this file](http://download.openstreetmap.fr/replication/europe/germany/nordrhein_westfalen/munster/minute/state.txt)) for the sequence id.

Or is there a way to disable the updates altogether? I only need the overpass container for bulk queries. I tried to comment out the portions `[program:fetch_diff]`, `[program:apply_diff]`, `[program:dispatcher_areas]` and `[program:areas_rules]` in [supervisord.conf](https://github.com/wiktorn/Overpass-API/blob/master/0.7.55/etc/supervisord.conf), then mounting the edited file into the container with `-v`, but sadly this resulted in almost the same error.

**Comment by wiktorn** [comment]
I didn't thought about running instance that's not updating itself, so this is something that's missing.

As for `sequenceNumber` I usually do this way, that I check the timestamp of `planet` file, then take sequence number that's a bit before this date. To find the sequence number, I navigate the directories in minute diffs, to find file that was modified at the data that I'm looking for.

So for example, If I have a dump file from 2019-02-23 04:00:00 am, I'd look for sequence file from midnight that day (using modified date), and it is this [file](http://download.openstreetmap.fr/replication/europe/germany/nordrhein_westfalen/munster/minute/003/378/535.state.txt). In the contents you'll have the sequence number.

It's good to have a sequence number not later than your dump so you'll not loose any objects that were created/updated between your planet dump file and since you're starting synchronization. Overlapping is not a problem, as the data will easily converge to current state.

Did it work properly when you set the sequence id?

**Comment by ubergesundheit** [comment]
Sorry for the late reply. I found out some stuff

It seems the `--meta` stuff does not work as expected. When setting it to `no`, the script `dispatcher_start.sh` does not work anymore. The empty string is being parsed as parameter which is then unknown to the actual `dispatcher` binary.

Also omitting the meta environment variable completely should have disabled the meta stuff but `.meta` files are generated nevertheless ?!

I have now done the following:

my `supervisord.conf`:

```ini
[supervisord]
nodaemon=true

[program:overpass_dispatch]
command=/bin/bash -c "find /db/db -type s -print0 | xargs -0 --no-run-if-empty rm && /app/bin/dispatcher --osm-base --db-dir=/db/db"
user=overpass
redirect_stderr=true
priority=1

[program:nginx]
command=nginx
priority=2

[program:fcgiwrap]
command=/bin/bash -c "find /nginx -type s -print0 | xargs -0 --no-run-if-empty rm && fcgiwrap -s unix:/nginx/fcgiwrap.socket"
redirect_stderr=true
user=nginx
priority=3
```

My `docker-entrypoint.sh`:

```bash
#!/bin/bash

set -eo pipefail
shopt -s nullglob
OVERPASS_COMPRESSION=${OVERPASS_COMPRESSION:-gz}

if [ ! -d /db/db ] ; then
  lftp -c "get -c \"$OVERPASS_PLANET_URL\" -o /db/planet; exit" \
  && /app/bin/init_osm3s.sh /db/planet /db/db /app "--compression-method=$OVERPASS_COMPRESSION" \
  && rm /db/planet \
  && cp -r /app/etc/rules /db/db \
  && chown -R overpass:overpass /db \
  && echo "Overpass ready, you can start your container with docker start"
  exit
fi

exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
```

**Comment by j8seangel** [comment]
I am struggling with the same issue, this is my `docker-compose.yml` 

```yml
version: '3'
services:
  api:
    image: wiktorn/overpass-api:latest
    container_name: overpass-api
    restart: always
    ports:
      - '12345:80'
    environment:
      - OVERPASS_META=yes
      - OVERPASS_MODE=init
      - OVERPASS_PLANET_URL=http://download.geofabrik.de/europe/spain-latest.osm.bz2
      - OVERPASS_DIFF_URL=http://download.openstreetmap.fr/replication/europe/spain/minute/
      - OVERPASS_PLANET_SEQUENCE_ID=3370000
    volumes:
      - /Workspace/docker/overpass_db/:/db
    stdin_open: true
    tty: true
```

I followed the steps to get the PLANET_SEQUENCE_ID and it didn't work, also tried with different META config and nothing, any idea to start investigating from?

**Comment by ubergesundheit** [comment]
You can check out my solution here:

https://github.com/codeformuenster/verkehrsunfaelle/blob/python-importer/docker-compose.yml

Also check out the files in the overpass directory in the same branch / repo

This assumes you want a container for single use.

**Comment by j8seangel** [comment]
It worked 🎉
A single use container is ok, thanks a lot @ubergesundheit !
