### ISSUE TITLE
Docker initialisation always failing for "Part of the World"

### ISSUE THREAD

**Issue by bwassermann** [wiktorn/Overpass-API#92]
Im currently trying to setup Germany as a Overpass-API on "Docker for Windows".
Docker has assigned 4 Cores, 16GB of RAM and 192GB Disk image size.

Im running the following command:
`docker run -e OVERPASS_META=no -e OVERPASS_MODE=init -e OVERPASS_PLANET_URL=http://download.geofabrik.de/europe/germany-latest.osm.bz2 -e OVERPASS_DIFF_URL=http://download.openstreetmap.fr/replication/europe/germany/minute/ -e OVERPASS_RULES_LOAD=10 -e OVERPASS_UPDATE_SLEEP=86400 -e OVERPASS_RULES_LOAD=10 -e OVERPASS_UPDATE_SLEEP=86400  -v /big/docker/overpass_db_germany/:/db -p 12345:80 -i -t --name overpass_germany wiktorn/overpass-api`

It always fails with "Broken Pipe" error during initialisation.

Im also tried it with the following command:
`docker run -e OVERPASS_META=no -e OVERPASS_MODE=init -e OVERPASS_PLANET_URL=http://download.openstreetmap.fr/extracts/europe/germany-latest.osm.pbf -e OVERPASS_DIFF_URL=http://download.openstreetmap.fr/replication/europe/germany/minute/ -e OVERPASS_COMPRESSION=gz  -e OVERPASS_PLANET_PREPROCESS='mv /db/planet.osm.bz2 /db/planet.osm.pbf && osmium cat -o /db/planet.osm.bz2 /db/planet.osm.pbf && rm /db/planet.osm.pbf' -e OVERPASS_RULES_LOAD=10 -e OVERPASS_UPDATE_SLEEP=86400  -v /big/docker/overpass_db_germany/:/db -p 12390:80 -i -t --name overpass_germany wiktorn/overpass-api`
Here it fails with "bzip2 error: write failed: -6" during the osmium task.

I also tried to add "-e OVERPASS_FLUSH_SIZE=1" - always the same error.

Do you have any ideas how i get it to work?

**Comment by wiktorn** [comment]
I would give it a try with more RAM. I have replica of Poland that runs with 16GB RAM and there wasn't much of headroom.
