### ISSUE TITLE
Error in query after building server clone

### ISSUE THREAD

**Issue by pedrocamargo** [wiktorn/Overpass-API#94]
I am currently trying to run a a container on a QNAP NAS (I have successfully done this in the past on this same device)  with a x86 processor and 40Gb of RAM.

The building of the server using the clone option went pretty smoothly, but I get this **runtime error: open64: /db/db/nodes.bin.idx File_Blocks_Index: Unsupported index file format version** error that also shows up when I try any query.

I scavenged GH and StackOverflow, but could not even find a reference to somebody having the same problem.

runtime error: open64: /db/db/nodes.bin.idx File_Blocks_Index: Unsupported index file format version
It took 0 to run the loop. Desired load is: 1%. Sleeping: 3
runtime error: open64: /db/db/nodes.bin.idx File_Blocks_Index: Unsupported index file format version
It took 0 to run the loop. Desired load is: 1%. Sleeping: 3
runtime error: open64: /db/db/nodes.bin.idx File_Blocks_Index: Unsupported index file format version
It took 0 to run the loop. Desired load is: 1%. Sleeping: 3
runtime error: open64: /db/db/nodes.bin.idx File_Blocks_Index: Unsupported index file format version
It took 0 to run the loop. Desired load is: 1%. Sleeping: 3
10.0.3.1 - - [01/Jun/2022:06:13:47 +0000] "GET / HTTP/1.1" 200 396 "-" "python-requests/2.25.0"
runtime error: open64: /db/db/nodes.bin.idx File_Blocks_Index: Unsupported index file format version
It took 0 to run the loop. Desired load is: 1%. Sleeping: 3
runtime error: open64: /db/db/nodes.bin.idx File_Blocks_Index: Unsupported index file format version
It took 0 to run the loop. Desired load is: 1%. Sleeping: 3
runtime error: open64: /db/db/nodes.bin.idx File_Blocks_Index: Unsupported index file format version
It took 1 to run the loop. Desired load is: 1%. Sleeping: 99
10.0.3.1 - - [01/Jun/2022:06:14:23 +0000] "GET / HTTP/1.1" 200 396 "-" "python-requests/2.25.0"
10.0.3.1 - - [01/Jun/2022:06:15:05 +0000] "GET / HTTP/1.1" 200 396 "-" "python-requests/2.25.0"
runtime error: open64: /db/db/nodes.bin.idx File_Blocks_Index: Unsupported index file format version
It took 0 to run the loop. Desired load is: 1%. Sleeping: 3
runtime error: open64: /db/db/nodes.bin.idx File_Blocks_Index: Unsupported index file format version
It took 0 to run the loop. Desired load is: 1%. Sleeping: 3
runtime error: open64: /db/db/nodes.bin.idx File_Blocks_Index: Unsupported index file format version
It took 0 to run the loop. Desired load is: 1%. Sleeping: 3

**Comment by MaRaSu** [comment]
@pedrocamargo I just run in the exactly same problem. I run the container on a Ubuntu x86 server, started also with the clone option. I have initialised with cloning exactly the same setup & config successfully +5 times in the past 2 years.

**Comment by richiemorrisroe-oh** [comment]
Looks like this is documented in the release notes for v 0.7.57: https://wiki.openstreetmap.org/wiki/Overpass_API/versions

It doesn't look like this version is available from Docker Hub, which seems to be the cause of the error (specifically when using replication).

**Comment by wiktorn** [comment]
I must have missed recent release announcements from Overpass team. New versions are available at Docker hub. Though I'm pretty confident that 0.7.57.1 was already available.

Please reopen if the issue persists.

**Comment by richiemorrisroe-oh** [comment]
You're totally right, it was under the `latest` tag. I assumed that `latest` was one of the older versions. 

In any case, the `latest` version resolved all of my issues. Thanks so much for your work on this!

**Comment by pedrocamargo** [comment]
It is working perfectly, and I think @richiemorrisroe-oh hit the nail on the head when raised the issue of the *latest* version being tagged to an older one.  It was probably the case!

**Comment by coachaac** [comment]
i have the same problem actually, using the `latest` tag.   
V0.57.9 has been released the 2022-10-14
