### ISSUE TITLE
How to improve query speed?

### ISSUE THREAD

**Issue by ArduinoHocam** [wiktorn/Overpass-API#96]
Hi,
I'm trying to send a query periodically relatively in high frequency ( ~5-10 Hz ). But there is a bottleneck for this which is the query response time.
When I try to query for a specific lat-lon with **around**, it is taking like 0.5 - 0.6 secs on Linux x86_64 machine Ubuntu 18.04 here is my example query command: curl "http://localhost/api/interpreter?data=%5Bout:json%5D%5Btimeout:25%5D;(way(around:5,52.29201,-1.51869)%5B"highway"%5D;._;>;);out;"

Is there a way to improve this query speed? I also removed the around keyword and added bbox coordinates, it was worse. 
I've actually tried a few parameters for docker : 
- OVERPASS_RULES_LOAD
- OVERPASS_TIME
But I think it did not make any difference. I've also tried to export only small region of map and compared with whole city and results are almost similar. I do not know exactly how the database side is handled and what kind of data structures etc. are used. So, is there a way to decrease this query execution time or this is more or less the maximum I can reach? 

Thanks.

**Comment by wiktorn** [comment]
Sorry, I missed this one. I don't look into performance of the Overpass itself. Hopefully Overpass team can help you with that.

**Comment by entropical** [comment]
Hey @ArduinoHocam, did you find any way to increase performance?
