### ISSUE TITLE
[Question] How to import offline data?

### ISSUE THREAD

**Issue by gaiyya** [wiktorn/Overpass-API#97]
I use following command to run;
`docker run -e DOWNLOAD_PBF=https://download.geofabrik.de/europe/monaco-
latest.osm.pbf -e DOWNLOAD_POLY=https://download.geofabrik.de/europe/monaco.poly -v
osm:/data/database/ overv/openstreetmap-tile-server import`

How do I use already downloaded pbf and poly file instead of downloading like above command?

**Comment by wiktorn** [comment]
If you already downloaded the file, make sure that it is visible somewhere within the container and you can use `file:///` URL scheme to refer to these files. They will still be copied inside the container, but at least that's disk-to-disk copy.
